version: "3.7"
services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'sport-api'
    ports:
      - "3306:3306"